def make_risk(
    rule_id,
    category,
    severity,
    message,
    recommendation="",
    components=None,
    nets=None,
    region=None,
    metrics=None,
    confidence=0.8,
    short_title="",
    fix_priority="medium",
    estimated_impact="moderate",
    design_domain="general",
):
    return {
        "rule_id": rule_id,
        "category": category,
        "severity": severity,
        "message": message,
        "recommendation": recommendation,
        "components": components or [],
        "nets": nets or [],
        "region": region,
        "metrics": metrics or {},
        "confidence": confidence,
        "short_title": short_title or message,
        "fix_priority": fix_priority,
        "estimated_impact": estimated_impact,
        "design_domain": design_domain,
    }