def make_risk(
    rule_id,
    category,
    severity,
    message,
    recommendation="",
    components=None,
    nets=None,
    region=None,
    metrics=None,
    confidence=0.8,
    short_title="",
    fix_priority="medium",
    estimated_impact="moderate",
    design_domain="general",
    why_it_matters="",
    suggested_actions=None,
    trigger_condition="",
    threshold_label="",
    observed_label="",
):
    return {
        "rule_id": rule_id,
        "category": category,
        "severity": severity,
        "message": message,
        "recommendation": recommendation,
        "components": components or [],
        "nets": nets or [],
        "region": region,
        "metrics": metrics or {},
        "confidence": confidence,
        "short_title": short_title or message,
        "fix_priority": fix_priority,
        "estimated_impact": estimated_impact,
        "design_domain": design_domain,
        "why_it_matters": why_it_matters,
        "suggested_actions": suggested_actions or [],
        "trigger_condition": trigger_condition,
        "threshold_label": threshold_label,
        "observed_label": observed_label,
    }
